# Generated by Django 4.0.3 on 2022-03-16 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='genre',
            field=models.ForeignKey(limit_choices_to=5, on_delete=django.db.models.deletion.CASCADE, to='books.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(limit_choices_to=5, on_delete=django.db.models.deletion.CASCADE, to='books.genre'),
        ),
    ]
