# Generated by Django 4.0.3 on 2022-03-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_author_genre_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(default='default_cover_pic.png', upload_to=''),
        ),
    ]
